export enum StatusCodeEnums {
    OK = 'OK',
    UNEXPECTED = 'UNEXPECTED',
    UNPROCESSABLE_ENTITY = 'UNPROCESSABLE_ENTITY',
    INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
    INVALID_TOKEN = 'INVALID_TOKEN',
    UNAUTHORIZED = 'UNAUTHORIZED',
    EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS',
    NOT_FOUND = 'NOT_FOUND'
}
